# -*- coding: utf-8 -*-
"""Netflix Movie Suggestions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zanAZ4e0t9Gv4cMiyVh9eU5nC9vcRgd5

Importing libraries
"""

!pip install apyori

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

"""Importing Dataset"""

dataset = pd.read_csv('/content/Netflix Movie Recommendation.csv', header = None, encoding='latin-1') # or encoding='ISO-8859-1' or encoding='cp1252'
transactions = []

for i in range(0, 7466):
  transactions.append([str(dataset.values[i,j]) for j in range(0, 20)])

"""Eclat Training on Dataset"""

from apyori import apriori
rules = apriori(transactions = transactions, min_support = 0.003, min_confidence = 0.2, min_lift = 3, min_length = 2, max_length = 2)

"""Visulaizing

Raw results
"""

results = list(rules)

results

"""Proper Display"""

def inspect(results):
    movie_1         = [tuple(result[2][0][0])[0] for result in results]
    movie_2         = [tuple(result[2][0][1])[0] for result in results]
    supports    = [result[1] for result in results]
    return list(zip(movie_1, movie_2, supports))
df = pd.DataFrame(inspect(results), columns = ['Movie 1', 'Movie 2', 'Support'])

df

# @title Distribution of Support for Movie Pairs

import matplotlib.pyplot as plt

# Assuming your data is in a pandas DataFrame called 'df'

plt.figure(figsize=(10, 6))
plt.scatter(df['Movie 1'], df['Movie 2'], s=df['Support'] * 10000, alpha=0.7)
plt.xlabel('Movie 1')
plt.ylabel('Movie 2')
plt.title('Distribution of Support for Movie Pairs')
plt.xticks(rotation=45, ha='right')
_ = plt.tight_layout()

# @title Frequency of Movie Pairings

import matplotlib.pyplot as plt
import seaborn as sns

# Assuming your data is in a pandas DataFrame called 'df'

df_heatmap = df.pivot_table(index='Movie 1', columns='Movie 2', values='Support', fill_value=0)

plt.figure(figsize=(10, 8))
ax = sns.heatmap(df_heatmap, annot=True, cmap='viridis')
plt.title('Frequency of Movie Pairings')
plt.xlabel('Movie 2')
_ = plt.ylabel('Movie 1')

# @title Support

from matplotlib import pyplot as plt
df['Support'].plot(kind='line', figsize=(8, 4), title='Support')
plt.gca().spines[['top', 'right']].set_visible(False)

# @title Movie 1 vs Movie 2

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['Movie 2'].value_counts()
    for x_label, grp in df.groupby('Movie 1')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('Movie 1')
_ = plt.ylabel('Movie 2')

resultsinDataFrame.nlargest(n = 10, columns = 'Support')

